services:
  sportchain-explorer:
    image: sportchain-explorer
    container_name: sportchain-explorer
    restart: unless-stopped
    environment:
      WS_URL: ${WS_URL:-}
    expose:
      - "80"
    networks:
      - atleta

networks:
  atleta:
    external: true
