version: "3"

services:
  nginx:
    image: sportchain-explorer
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: sportchain-explorer
    restart: unless-stopped
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./certbot/www:/var/www/certbot:ro
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    networks:
      - sportchain-explorer-network

  certbot:
    image: certbot/certbot:v2.10.0
    container_name: sportchain-explorer-certbot
    restart: unless-stopped
    volumes:
      - ./nginx/ssl:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; certbot certonly --standalone --preferred-challenges http -d $$CERTBOT_DOMAIN --email $$CERTBOT_EMAIL --agree-tos --non-interactive --verbose; sleep 12h'"
    environment:
      - CERTBOT_EMAIL=admin@moneyfactory.io
      - CERTBOT_DOMAIN=polkadot-explorer.atleta.network


networks:
  sportchain-explorer-network: {}
