version: "3"

services:
  sportchain-explorer:
    image: sportchain-explorer
    container_name: sportchain-explorer
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - atleta

networks:
  atleta:
    external: true
