name: Deploy Explorer

on:
  push:
    branches: [ "atleta" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "recursive"

    - name: Create Image Tarball for Explorer
      run: |
        docker compose -f docker/docker-compose.yaml build
        docker save -o sportchain-explorer.tar sportchain-explorer
        mkdir -p artifacts/
        mv sportchain-explorer.tar artifacts/

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets.EXPLORER_HOST }} >> ~/.ssh/known_hosts
        echo "${{ secrets.EXPLORER_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)

    - name: Copy Files to Server
      run: |
        scp artifacts/sportchain-explorer.tar ${{ secrets.EXPLORER_USERNAME}}@${{ secrets.EXPLORER_HOST }}:/sportchain/
        scp docker-compose.yaml ${{ secrets.EXPLORER_USERNAME}}@${{ secrets.EXPLORER_HOST }}:/sportchain/docker-compose.yaml

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EXPLORER_HOST }}
        username: ${{ secrets.EXPLORER_USERNAME }}
        key: ${{ secrets.EXPLORER_PRIVATE_KEY }}
        script: |
          cd /sportchain
          docker load -i sportchain-explorer.tar
          docker compose up -d
