name: 'Upstream Sync'

permissions:
  contents: write
  actions: write
  pull-requests: write

on:
  pull_request:

  schedule:
    - cron:  '0 7 * * 1'
    # scheduled at 07:00 every Monday

  workflow_dispatch:  # click the button on Github repo!
    inputs:
      sync_test_mode: # Adds a boolean option that appears during manual workflow run for easy test mode config
        description: 'Fork Sync Test Mode'
        type: boolean
        default: false

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        # optional: set the branch to checkout,
        ref: upstream
        token: ${{ github.token }}
        # persist-credentials: false

    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: upstream
        target_repo_token: ${{ github.token }}
        upstream_sync_branch: master
        upstream_sync_repo: polkadot-js/apps

        # Set test_mode true during manual dispatch to run tests instead of the true action!!
        test_mode: ${{ inputs.sync_test_mode }}

    # Display a sample message based on the sync output var 'has_new_commits'
    - name: New commits found
      id: last_commit
      if: steps.sync.outputs.has_new_commits == 'true'
      run: | 
        echo "New commits were found to sync."

    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."

    - name: Check if PR already exists
      id: check_pr_exists
      env: 
        GH_TOKEN: ${{ github.token }}
      run: |
        pr_count=$(gh pr list --repo ${{ github.repository }} --json 'headRefName' --jq 'map(select(.headRefName == "upstream")) | length')
        echo "pr_count=${pr_count}" >> $GITHUB_ENV

    - name: Create Pull Request
      if: steps.sync.outputs.has_new_commits == 'true' && steps.check_pr_exists.outputs.pr_count == '0'
      env: 
        GH_TOKEN: ${{ github.token }}
      run: |
        WORKFLOW_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        gh pr create --repo ${{ github.repository }} --title "Upstream Sync" --body "[View Workflow Run](${WORKFLOW_URL})" --head upstream --base test-auto-pr --reviewer ${{ secrets.REVIEWER_1 }} 
